### PR TITLE
created user interface statements for milestone project 2

### PR DESCRIPTION
**Pull request by gitnyasha**
created user prompts

### CODE REVIEW

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @gitnyasha,
Great job so far 👏👏, however, there are a few things that are missing for this to be approved.
- [ ] A loop is needed in this game, check this screenshot of an [OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)
- The loop should be terminated at some point (after a winning move or a draw ).
- [ ] You should have a basic game flow see the screenshot of [the hint from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png). Your game flow should have these steps.
- The game tells which player's turn it is
- The game asks player to select from available moves
- The game informs player if the selected move is invalid
- The game displays board after the player's move
- The game informs player if the selected move is a winning move
- The game informs player if the selected move is a draw move
- The game repeats all actions for the next player's move


 [OPTIONAL]
- The game asks players for their names

### Kindly make the suggested changes then request for another code review
### Status: Changes Required 🛑
_Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._

**Comment by gitnyasha** [comment]
> ## Hi @gitnyasha,
> 
> Great job so far clapclap, however, there are a few things that are missing for this to be approved.
> 
>     * [ ]  A loop is needed in this game, check this screenshot of an [OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)
> 
>     * The loop should be terminated at some point (after a winning move or a draw ).
> 
>     * [ ]  You should have a basic game flow see the screenshot of [the hint from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png). Your game flow should have these steps.
> 
>     * The game tells which player's turn it is
> 
>     * The game asks player to select from available moves
> 
>     * The game informs player if the selected move is invalid
> 
>     * The game displays board after the player's move
> 
>     * The game informs player if the selected move is a winning move
> 
>     * The game informs player if the selected move is a draw move
> 
>     * The game repeats all actions for the next player's move
> 
> 
> [OPTIONAL]
> 
>     * The game asks players for their names
> 
> 
> ### Kindly make the suggested changes then request for another code review
> ### Status: Changes Required stop_sign
> 
> _Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._


Based on the instructions below are those changes required

- Display prompts for users (hint: puts/print), collect user input (hint: get.chomp) and only mock the basic flow of the game (you can use puts or inline comments to say for example “Now, your move is displayed on the board”).
- Make sure that you can run your game with your executable file and play with the basic flow.
- The final point of this milestone is to make sure that you thought about all actions needed to play Tic Tac Toe. It does not need to work yet - this will be done in the next milestone.

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @gitnyasha, 👋 

### Great job thus far! 🙌 The readME also looks professional. Kindly fix all the TSE suggestions.

* [ ] Your `main.rb` file is missing the `.rb` extension.

##### Behaviour
There are some bugs when playing your game, it plays in the wrong position. Please use the checklist below to test your code:

* [ ] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  * [ ] `[OPTIONAL]` game ask players for their names
  * [ ] `[REQUIRED]` game tells which player turn it is
  * [ ] `[REQUIRED]` game asks player to select from available moves
  * [ ] `[REQUIRED]` game informs player if selected move is invalid
  * [ ] `[REQUIRED]` game displays board after player move
  * [ ] `[REQUIRED]` game informs player if selected move is a winning move
  * [ ] `[REQUIRED]` game informs player if selected move is a draw move
  * [ ] `[REQUIRED]` game repeats all actions for next player's move

**Kindly submit for another review once these have been fixed.** _Happy coding!_ 🎉

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi @gitnyasha ! Nice job!
### Kindly recommended doing all changes required previously in review!



### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*


*Happy coding 😄*

**Comment by gitnyasha** [comment]
> ### Hi @gitnyasha ! Nice job!
> ### Kindly recommended doing all changes required previously in review!
> ### Make changes and submit another code review request.
> 
> _If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you._
> 
> _Happy coding smile_

It's not relevant

**Pull request closed without merging**
